name: Example Workflow

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}" >> $GITHUB_ENV
          echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_KEY }}" >> $GITHUB_ENV

        

      - name: Run script
        run: python bot.py